services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    networks:
      - rag-network
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      OPENAI_ENDPOINT: ${OPENAI_ENDPOINT}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_API_VERSION: ${OPENAI_API_VERSION}
      OPENAI_CHAT_MODEL: ${OPENAI_CHAT_MODEL}
      OPENAI_EMBEDDING_MODEL: ${OPENAI_EMBEDDING_MODEL}
      OPENAI_TYPE: ${OPENAI_TYPE}
      QDRANT_ENDPOINT: ${QDRANT_ENDPOINT}
      QDRANT_PORT: ${QDRANT_PORT}
      QDRANT_COLLECTION_NAME: ${QDRANT_COLLECTION_NAME}
      AZURE_OCR_ENDPOINT: ${AZURE_OCR_ENDPOINT}
      AZURE_OCR_KEY: ${AZURE_OCR_KEY}
    depends_on:
      - qdrant
    networks:
      - rag-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    environment:
      BACKEND_URL: ${BACKEND_URL}
    depends_on:
      - backend
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge