openapi: 3.0.0
info:
  title: RAG System
  version: 0.1.0
paths:
  /question:
    post:
      tags:
        - Consult
      summary: Consult Files
      operationId: consult_files_question_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConsultRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsultResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /documents:
    post:
      tags:
        - Document Ingestion
      summary: Upload Documents
      description: |-
        Upload one or more PDF documents.

        Args:
            files: List of PDF files to be uploaded

        Returns:
            dict: Status of the upload operation
      operationId: upload_documents_documents_post
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_upload_documents_documents_post'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngestionResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    Body_upload_documents_documents_post:
      properties:
        files:
          items:
            type: string
            format: binary
          type: array
          title: Files
      type: object
      required:
        - files
      title: Body_upload_documents_documents_post
    ConsultRequest:
      properties:
        question:
          type: string
          title: Question
      type: object
      required:
        - question
      title: ConsultRequest
    ConsultResponse:
      properties:
        answer:
          type: string
          title: Answer
        references:
          items:
            type: string
          type: array
          title: References
      type: object
      required:
        - answer
        - references
      title: ConsultResponse
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    IngestionResponse:
      properties:
        message:
          type: string
          title: Message
        documents_indexed:
          type: integer
          title: Documents Indexed
        total_chunks:
          type: integer
          title: Total Chunks
      type: object
      required:
        - message
        - documents_indexed
        - total_chunks
      title: IngestionResponse
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
